# Generated by Django 3.2 on 2021-04-26 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions_catalog', '0005_auto_20210424_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questions_catalog.question'),
        ),
    ]
